baseURL = 'https://aramide.dev'
languageCode = 'en-gb'
title = 'Tobiloba Ogundiyan'
defaultContentLanguage = "en-gb"


theme = 'rusty-typewriter'


[params.rtwt.side.home]
taxonomies = ['tags','series']  # What shows in the sidebar
countTaxonomy = 4  # How many tags/series to display
showBio = true
showAuthorImg = false
sidePaneTags = true


[outputs]
home = ["HTML", "RSS", "SearchIndex"]

[taxonomies]
tag = 'tags'
topic = 'topics'
series = 'series'

[params.author]
name = 'Tobiloba Ogundiyan'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 1

[[menus.main]]
name = 'Features'
pageRef = '/features'
weight = 2

[[menus.main]]
name = 'About'
pageRef = '/about-tobiloba-ogundiyan.md'
weight = 3



